export interface Question {
  id: number
  category: string
  question: string
  questionEn: string
  options: string[]
  optionsEn: string[]
  correctAnswer: number
  explanation: string
  explanationEn: string
}

export const questions: Question[] = [
  // JavaScript - 10 вопросов
  {
    id: 1,
    category: 'JavaScript',
    question: 'Что такое замыкание (closure) в JavaScript?',
    questionEn: 'What is a closure in JavaScript?',
    options: [
      'Функция, которая имеет доступ к переменным внешней области видимости',
      'Способ изоляции переменных',
      'Метод оптимизации кода',
      'Тип данных в JavaScript',
    ],
    optionsEn: [
      'A function that has access to variables from the outer scope',
      'A way to isolate variables',
      'A code optimization method',
      'A data type in JavaScript',
    ],
    correctAnswer: 0,
    explanation: 'Замыкание - это функция, которая имеет доступ к переменным внешней (охватывающей) области видимости, даже после того, как внешняя функция завершила выполнение.',
    explanationEn: 'A closure is a function that has access to variables from the outer (enclosing) scope, even after the outer function has finished executing.',
  },
  {
    id: 2,
    category: 'JavaScript',
    question: 'Что выведет console.log(typeof null)?',
    questionEn: 'What will console.log(typeof null) output?',
    options: ['null', 'undefined', 'object', 'boolean'],
    optionsEn: ['null', 'undefined', 'object', 'boolean'],
    correctAnswer: 2,
    explanation: 'Это известная особенность JavaScript - typeof null возвращает "object", хотя null является примитивным значением. Это баг, который сохраняется для обратной совместимости.',
    explanationEn: 'This is a well-known JavaScript quirk - typeof null returns "object", although null is a primitive value. This is a bug that persists for backward compatibility.',
  },
  {
    id: 3,
    category: 'JavaScript',
    question: 'Что такое hoisting в JavaScript?',
    questionEn: 'What is hoisting in JavaScript?',
    options: [
      'Перемещение объявлений переменных и функций наверх области видимости',
      'Оптимизация кода браузером',
      'Способ создания функций',
      'Метод работы с DOM',
    ],
    optionsEn: [
      'Moving variable and function declarations to the top of their scope',
      'Code optimization by the browser',
      'A way to create functions',
      'A method for working with DOM',
    ],
    correctAnswer: 0,
    explanation: 'Hoisting - это механизм JavaScript, при котором объявления переменных и функций перемещаются в начало их области видимости на этапе компиляции.',
    explanationEn: 'Hoisting is a JavaScript mechanism where variable and function declarations are moved to the top of their scope during the compilation phase.',
  },
  {
    id: 4,
    category: 'JavaScript',
    question: 'Какая разница между let и var?',
    questionEn: 'What is the difference between let and var?',
    options: [
      'let имеет блочную область видимости, var - функциональную',
      'Нет разницы',
      'var быстрее let',
      'let можно переопределять, var нельзя',
    ],
    optionsEn: [
      'let has block scope, var has function scope',
      'No difference',
      'var is faster than let',
      'let can be redeclared, var cannot',
    ],
    correctAnswer: 0,
    explanation: 'let имеет блочную область видимости (внутри {}), в то время как var имеет функциональную область видимости. Также let не поднимается (hoist) так же, как var.',
    explanationEn: 'let has block scope (within {}), while var has function scope. Also, let is not hoisted in the same way as var.',
  },
  {
    id: 5,
    category: 'JavaScript',
    question: 'Что такое Promise в JavaScript?',
    questionEn: 'What is a Promise in JavaScript?',
    options: [
      'Объект, представляющий результат асинхронной операции',
      'Тип данных для хранения чисел',
      'Метод для работы с DOM',
      'Способ объявления переменных',
    ],
    optionsEn: [
      'An object representing the result of an asynchronous operation',
      'A data type for storing numbers',
      'A method for working with DOM',
      'A way to declare variables',
    ],
    correctAnswer: 0,
    explanation: 'Promise - это объект, который представляет завершение (или неудачу) асинхронной операции и её результирующее значение.',
    explanationEn: 'A Promise is an object that represents the completion (or failure) of an asynchronous operation and its resulting value.',
  },
  {
    id: 6,
    category: 'JavaScript',
    question: 'Что делает метод Array.prototype.map()?',
    questionEn: 'What does the Array.prototype.map() method do?',
    options: [
      'Создаёт новый массив с результатами вызова функции для каждого элемента',
      'Фильтрует элементы массива',
      'Сортирует массив',
      'Находит элемент в массиве',
    ],
    optionsEn: [
      'Creates a new array with the results of calling a function for each element',
      'Filters array elements',
      'Sorts the array',
      'Finds an element in the array',
    ],
    correctAnswer: 0,
    explanation: 'Метод map() создаёт новый массив с результатами вызова указанной функции для каждого элемента исходного массива.',
    explanationEn: 'The map() method creates a new array with the results of calling a provided function on every element in the original array.',
  },
  {
    id: 7,
    category: 'JavaScript',
    question: 'Что такое Event Loop в JavaScript?',
    questionEn: 'What is the Event Loop in JavaScript?',
    options: [
      'Механизм обработки асинхронных операций',
      'Цикл для перебора массивов',
      'Событие клика мыши',
      'Тип данных',
    ],
    optionsEn: [
      'A mechanism for handling asynchronous operations',
      'A loop for iterating over arrays',
      'A mouse click event',
      'A data type',
    ],
    correctAnswer: 0,
    explanation: 'Event Loop - это механизм, который позволяет JavaScript выполнять асинхронные операции, несмотря на то, что JS однопоточный.',
    explanationEn: 'The Event Loop is a mechanism that allows JavaScript to perform asynchronous operations despite JS being single-threaded.',
  },
  {
    id: 8,
    category: 'JavaScript',
    question: 'Что такое деструктуризация в JavaScript?',
    questionEn: 'What is destructuring in JavaScript?',
    options: [
      'Извлечение значений из массивов или объектов в отдельные переменные',
      'Удаление элементов из массива',
      'Создание копии объекта',
      'Метод сортировки',
    ],
    optionsEn: [
      'Extracting values from arrays or objects into separate variables',
      'Removing elements from an array',
      'Creating a copy of an object',
      'A sorting method',
    ],
    correctAnswer: 0,
    explanation: 'Деструктуризация позволяет извлекать значения из массивов или свойства из объектов и присваивать их отдельным переменным.',
    explanationEn: 'Destructuring allows you to extract values from arrays or properties from objects and assign them to separate variables.',
  },
  {
    id: 9,
    category: 'JavaScript',
    question: 'Что такое стрелочные функции?',
    questionEn: 'What are arrow functions?',
    options: [
      'Краткий синтаксис для функций без собственного this',
      'Функции для работы с массивами',
      'Устаревший способ объявления функций',
      'Функции, которые возвращают стрелки',
    ],
    optionsEn: [
      'A concise syntax for functions without their own this',
      'Functions for working with arrays',
      'An outdated way to declare functions',
      'Functions that return arrows',
    ],
    correctAnswer: 0,
    explanation: 'Стрелочные функции - это краткий синтаксис для написания функций. Они не имеют собственного this и используют this из окружающего контекста.',
    explanationEn: 'Arrow functions are a concise syntax for writing functions. They do not have their own this and use this from the surrounding context.',
  },
  {
    id: 10,
    category: 'JavaScript',
    question: 'Что такое spread оператор (...)?',
    questionEn: 'What is the spread operator (...)?',
    options: [
      'Разворачивает массив или объект в отдельные элементы',
      'Создаёт массив из элементов',
      'Удаляет элементы из массива',
      'Сравнивает два массива',
    ],
    optionsEn: [
      'Expands an array or object into individual elements',
      'Creates an array from elements',
      'Removes elements from an array',
      'Compares two arrays',
    ],
    correctAnswer: 0,
    explanation: 'Spread оператор (...) позволяет развернуть итерируемый объект (массив, строку) в местах, где ожидается ноль или более аргументов или элементов.',
    explanationEn: 'The spread operator (...) allows you to expand an iterable (array, string) in places where zero or more arguments or elements are expected.',
  },

  // React - 10 вопросов
  {
    id: 11,
    category: 'React',
    question: 'В чем разница между useState и useReducer?',
    questionEn: 'What is the difference between useState and useReducer?',
    options: [
      'useState для простого состояния, useReducer для сложной логики',
      'useState быстрее, чем useReducer',
      'useReducer только для массивов',
      'Нет разницы',
    ],
    optionsEn: [
      'useState is for simple state, useReducer is for complex logic',
      'useState is faster than useReducer',
      'useReducer is only for arrays',
      'No difference',
    ],
    correctAnswer: 0,
    explanation: 'useState подходит для простого локального состояния, а useReducer лучше использовать когда логика обновления состояния сложная или когда следующее состояние зависит от предыдущего.',
    explanationEn: 'useState is suitable for simple local state, while useReducer is better when state update logic is complex or when the next state depends on the previous one.',
  },
  {
    id: 12,
    category: 'React',
    question: 'Что такое виртуальный DOM?',
    questionEn: 'What is the Virtual DOM?',
    options: [
      'Легковесная копия реального DOM в памяти',
      'Способ рендеринга на сервере',
      'Тип компонента React',
      'Метод оптимизации CSS',
    ],
    optionsEn: [
      'A lightweight copy of the real DOM in memory',
      'A server-side rendering method',
      'A type of React component',
      'A CSS optimization method',
    ],
    correctAnswer: 0,
    explanation: 'Виртуальный DOM - это легковесная копия реального DOM, хранящаяся в памяти. React использует его для эффективного обновления только измененных частей реального DOM.',
    explanationEn: 'The Virtual DOM is a lightweight copy of the real DOM stored in memory. React uses it to efficiently update only the changed parts of the real DOM.',
  },
  {
    id: 13,
    category: 'React',
    question: 'Что такое useEffect?',
    questionEn: 'What is useEffect?',
    options: [
      'Хук для выполнения побочных эффектов в компонентах',
      'Метод для создания компонентов',
      'Способ стилизации компонентов',
      'Инструмент для тестирования',
    ],
    optionsEn: [
      'A hook for performing side effects in components',
      'A method for creating components',
      'A way to style components',
      'A testing tool',
    ],
    correctAnswer: 0,
    explanation: 'useEffect - это хук, который позволяет выполнять побочные эффекты в функциональных компонентах: запросы к API, подписки, изменение DOM и т.д.',
    explanationEn: 'useEffect is a hook that allows you to perform side effects in functional components: API requests, subscriptions, DOM changes, etc.',
  },
  {
    id: 14,
    category: 'React',
    question: 'Что такое props в React?',
    questionEn: 'What are props in React?',
    options: [
      'Данные, передаваемые от родительского компонента к дочернему',
      'Внутреннее состояние компонента',
      'Стили компонента',
      'Методы жизненного цикла',
    ],
    optionsEn: [
      'Data passed from parent component to child component',
      'Internal component state',
      'Component styles',
      'Lifecycle methods',
    ],
    correctAnswer: 0,
    explanation: 'Props (properties) - это механизм передачи данных от родительского компонента к дочернему. Props неизменяемы внутри компонента.',
    explanationEn: 'Props (properties) are a mechanism for passing data from a parent component to a child component. Props are immutable within the component.',
  },
  {
    id: 15,
    category: 'React',
    question: 'Что такое JSX?',
    questionEn: 'What is JSX?',
    options: [
      'Синтаксическое расширение JavaScript для описания UI',
      'Библиотека для работы с формами',
      'Фреймворк для тестирования',
      'Система сборки',
    ],
    optionsEn: [
      'A syntactic extension of JavaScript for describing UI',
      'A library for working with forms',
      'A testing framework',
      'A build system',
    ],
    correctAnswer: 0,
    explanation: 'JSX - это синтаксическое расширение JavaScript, которое позволяет писать HTML-подобный код внутри JavaScript для описания UI.',
    explanationEn: 'JSX is a syntactic extension of JavaScript that allows you to write HTML-like code inside JavaScript to describe UI.',
  },
  {
    id: 16,
    category: 'React',
    question: 'Зачем нужен key в списках React?',
    questionEn: 'Why is the key prop needed in React lists?',
    options: [
      'Для идентификации элементов при обновлении списка',
      'Для стилизации элементов',
      'Для сортировки списка',
      'Для доступа к элементам по индексу',
    ],
    optionsEn: [
      'To identify elements when updating the list',
      'To style elements',
      'To sort the list',
      'To access elements by index',
    ],
    correctAnswer: 0,
    explanation: 'Key помогает React идентифицировать элементы, которые изменились, добавились или удалились. Это повышает производительность при обновлении списков.',
    explanationEn: 'Key helps React identify which elements have changed, been added, or removed. This improves performance when updating lists.',
  },
  {
    id: 17,
    category: 'React',
    question: 'Что такое React Context?',
    questionEn: 'What is React Context?',
    options: [
      'Способ передачи данных через дерево компонентов без props',
      'Метод для работы с формами',
      'Хук для работы с состоянием',
      'Библиотека маршрутизации',
    ],
    optionsEn: [
      'A way to pass data through the component tree without props',
      'A method for working with forms',
      'A hook for state management',
      'A routing library',
    ],
    correctAnswer: 0,
    explanation: 'Context предоставляет способ передачи данных через дерево компонентов без необходимости передавать props на каждом уровне вручную.',
    explanationEn: 'Context provides a way to pass data through the component tree without having to pass props manually at every level.',
  },
  {
    id: 18,
    category: 'React',
    question: 'Что такое useMemo?',
    questionEn: 'What is useMemo?',
    options: [
      'Хук для мемоизации вычисляемых значений',
      'Хук для управления состоянием',
      'Метод для создания компонентов',
      'Инструмент для отладки',
    ],
    optionsEn: [
      'A hook for memoizing computed values',
      'A hook for state management',
      'A method for creating components',
      'A debugging tool',
    ],
    correctAnswer: 0,
    explanation: 'useMemo - это хук, который мемоизирует результат вычисления и пересчитывает его только при изменении зависимостей. Используется для оптимизации производительности.',
    explanationEn: 'useMemo is a hook that memoizes the result of a computation and recalculates it only when dependencies change. Used for performance optimization.',
  },
  {
    id: 19,
    category: 'React',
    question: 'Что такое useCallback?',
    questionEn: 'What is useCallback?',
    options: [
      'Хук для мемоизации функций',
      'Хук для обработки ошибок',
      'Метод для создания событий',
      'Инструмент для работы с API',
    ],
    optionsEn: [
      'A hook for memoizing functions',
      'A hook for error handling',
      'A method for creating events',
      'A tool for working with APIs',
    ],
    correctAnswer: 0,
    explanation: 'useCallback - это хук, который возвращает мемоизированную версию колбэк-функции, которая изменяется только при изменении зависимостей.',
    explanationEn: 'useCallback is a hook that returns a memoized version of the callback function that only changes when dependencies change.',
  },
  {
    id: 20,
    category: 'React',
    question: 'Что такое React.memo?',
    questionEn: 'What is React.memo?',
    options: [
      'HOC для предотвращения ненужных перерендеров компонента',
      'Хук для работы с памятью',
      'Метод для создания заметок',
      'Инструмент для логирования',
    ],
    optionsEn: [
      'A HOC for preventing unnecessary component re-renders',
      'A hook for memory management',
      'A method for creating notes',
      'A logging tool',
    ],
    correctAnswer: 0,
    explanation: 'React.memo - это компонент высшего порядка (HOC), который предотвращает ненужные перерендеры компонента, если его props не изменились.',
    explanationEn: 'React.memo is a higher-order component (HOC) that prevents unnecessary re-renders of a component if its props have not changed.',
  },

  // Алгоритмы - 10 вопросов
  {
    id: 21,
    category: 'Algorithms',
    question: 'Какая временная сложность у бинарного поиска?',
    questionEn: 'What is the time complexity of binary search?',
    options: ['O(n)', 'O(log n)', 'O(n log n)', 'O(1)'],
    optionsEn: ['O(n)', 'O(log n)', 'O(n log n)', 'O(1)'],
    correctAnswer: 1,
    explanation: 'Бинарный поиск имеет временную сложность O(log n), так как на каждой итерации мы уменьшаем область поиска вдвое.',
    explanationEn: 'Binary search has a time complexity of O(log n) because we halve the search area on each iteration.',
  },
  {
    id: 22,
    category: 'Algorithms',
    question: 'Какая структура данных используется для реализации очереди (queue)?',
    questionEn: 'What data structure is used to implement a queue?',
    options: ['Стек', 'Массив', 'Связанный список', 'Дерево'],
    optionsEn: ['Stack', 'Array', 'Linked list', 'Tree'],
    correctAnswer: 2,
    explanation: 'Очередь обычно реализуется с помощью связанного списка, так как добавление и удаление элементов происходит за O(1) на обоих концах.',
    explanationEn: 'A queue is usually implemented with a linked list because adding and removing elements takes O(1) at both ends.',
  },
  {
    id: 23,
    category: 'Algorithms',
    question: 'Что такое Big O нотация?',
    questionEn: 'What is Big O notation?',
    options: [
      'Способ описания временной или пространственной сложности алгоритма',
      'Название алгоритма сортировки',
      'Тип структуры данных',
      'Метод оптимизации кода',
    ],
    optionsEn: [
      'A way to describe the time or space complexity of an algorithm',
      'The name of a sorting algorithm',
      'A type of data structure',
      'A code optimization method',
    ],
    correctAnswer: 0,
    explanation: 'Big O нотация используется для описания верхней границы временной или пространственной сложности алгоритма при увеличении размера входных данных.',
    explanationEn: 'Big O notation is used to describe the upper bound of the time or space complexity of an algorithm as the input size increases.',
  },
  {
    id: 24,
    category: 'Algorithms',
    question: 'Какая временная сложность у bubble sort в худшем случае?',
    questionEn: 'What is the worst-case time complexity of bubble sort?',
    options: ['O(n)', 'O(log n)', 'O(n²)', 'O(n log n)'],
    optionsEn: ['O(n)', 'O(log n)', 'O(n²)', 'O(n log n)'],
    correctAnswer: 2,
    explanation: 'Bubble sort имеет временную сложность O(n²) в худшем случае, так как для каждого элемента нужно пройти весь массив.',
    explanationEn: 'Bubble sort has a time complexity of O(n²) in the worst case because for each element we need to traverse the entire array.',
  },
  {
    id: 25,
    category: 'Algorithms',
    question: 'Что такое хеш-таблица?',
    questionEn: 'What is a hash table?',
    options: [
      'Структура данных с O(1) доступом по ключу',
      'Отсортированный массив',
      'Тип дерева',
      'Метод сортировки',
    ],
    optionsEn: [
      'A data structure with O(1) access by key',
      'A sorted array',
      'A type of tree',
      'A sorting method',
    ],
    correctAnswer: 0,
    explanation: 'Хеш-таблица - это структура данных, которая обеспечивает в среднем O(1) время для операций вставки, удаления и поиска по ключу.',
    explanationEn: 'A hash table is a data structure that provides average O(1) time for insert, delete, and lookup operations by key.',
  },
  {
    id: 26,
    category: 'Algorithms',
    question: 'Что такое рекурсия?',
    questionEn: 'What is recursion?',
    options: [
      'Вызов функцией самой себя',
      'Цикл for',
      'Сортировка массива',
      'Поиск в массиве',
    ],
    optionsEn: [
      'A function calling itself',
      'A for loop',
      'Sorting an array',
      'Searching in an array',
    ],
    correctAnswer: 0,
    explanation: 'Рекурсия - это подход, при котором функция вызывает сама себя для решения подзадач. Требует базовый случай для завершения.',
    explanationEn: 'Recursion is an approach where a function calls itself to solve subproblems. It requires a base case to terminate.',
  },
  {
    id: 27,
    category: 'Algorithms',
    question: 'Какая временная сложность у quick sort в среднем?',
    questionEn: 'What is the average time complexity of quick sort?',
    options: ['O(n)', 'O(log n)', 'O(n²)', 'O(n log n)'],
    optionsEn: ['O(n)', 'O(log n)', 'O(n²)', 'O(n log n)'],
    correctAnswer: 3,
    explanation: 'Quick sort имеет среднюю временную сложность O(n log n), что делает его одним из самых эффективных алгоритмов сортировки.',
    explanationEn: 'Quick sort has an average time complexity of O(n log n), making it one of the most efficient sorting algorithms.',
  },
  {
    id: 28,
    category: 'Algorithms',
    question: 'Что такое стек (stack)?',
    questionEn: 'What is a stack?',
    options: [
      'Структура данных LIFO (последний вошёл - первый вышел)',
      'Структура данных FIFO',
      'Тип массива',
      'Метод сортировки',
    ],
    optionsEn: [
      'A LIFO (Last In, First Out) data structure',
      'A FIFO data structure',
      'A type of array',
      'A sorting method',
    ],
    correctAnswer: 0,
    explanation: 'Стек - это структура данных, работающая по принципу LIFO (Last In, First Out). Последний добавленный элемент извлекается первым.',
    explanationEn: 'A stack is a data structure that works on the LIFO (Last In, First Out) principle. The last added element is retrieved first.',
  },
  {
    id: 29,
    category: 'Algorithms',
    question: 'Что такое граф в программировании?',
    questionEn: 'What is a graph in programming?',
    options: [
      'Структура данных из вершин и рёбер',
      'Визуальное представление данных',
      'Тип массива',
      'Метод сортировки',
    ],
    optionsEn: [
      'A data structure consisting of vertices and edges',
      'A visual representation of data',
      'A type of array',
      'A sorting method',
    ],
    correctAnswer: 0,
    explanation: 'Граф - это структура данных, состоящая из вершин (узлов) и рёбер (связей между узлами). Используется для моделирования связей между объектами.',
    explanationEn: 'A graph is a data structure consisting of vertices (nodes) and edges (connections between nodes). Used to model relationships between objects.',
  },
  {
    id: 30,
    category: 'Algorithms',
    question: 'Что такое динамическое программирование?',
    questionEn: 'What is dynamic programming?',
    options: [
      'Метод решения задач путём разбиения на подзадачи с мемоизацией',
      'Программирование на динамических языках',
      'Создание анимаций',
      'Работа с базами данных',
    ],
    optionsEn: [
      'A method for solving problems by breaking them into subproblems with memoization',
      'Programming in dynamic languages',
      'Creating animations',
      'Working with databases',
    ],
    correctAnswer: 0,
    explanation: 'Динамическое программирование - это метод решения сложных задач путём разбиения их на более простые подзадачи с сохранением результатов для избежания повторных вычислений.',
    explanationEn: 'Dynamic programming is a method for solving complex problems by breaking them into simpler subproblems and storing results to avoid repeated calculations.',
  },

  // Базы данных - 10 вопросов
  {
    id: 31,
    category: 'Databases',
    question: 'Что такое нормализация базы данных?',
    questionEn: 'What is database normalization?',
    options: [
      'Процесс организации данных для уменьшения избыточности',
      'Увеличение производительности запросов',
      'Создание резервных копий',
      'Шифрование данных',
    ],
    optionsEn: [
      'The process of organizing data to reduce redundancy',
      'Increasing query performance',
      'Creating backups',
      'Data encryption',
    ],
    correctAnswer: 0,
    explanation: 'Нормализация - это процесс организации данных в базе данных для уменьшения избыточности и улучшения целостности данных.',
    explanationEn: 'Normalization is the process of organizing data in a database to reduce redundancy and improve data integrity.',
  },
  {
    id: 32,
    category: 'Databases',
    question: 'Что такое ACID в контексте транзакций?',
    questionEn: 'What is ACID in the context of transactions?',
    options: [
      'Atomicity, Consistency, Isolation, Durability',
      'Метод индексации',
      'Тип базы данных',
      'Язык запросов',
    ],
    optionsEn: [
      'Atomicity, Consistency, Isolation, Durability',
      'An indexing method',
      'A type of database',
      'A query language',
    ],
    correctAnswer: 0,
    explanation: 'ACID - это набор свойств транзакций: Atomicity (атомарность), Consistency (согласованность), Isolation (изоляция), Durability (долговечность).',
    explanationEn: 'ACID is a set of transaction properties: Atomicity, Consistency, Isolation, and Durability.',
  },
  {
    id: 33,
    category: 'Databases',
    question: 'Что такое SQL?',
    questionEn: 'What is SQL?',
    options: [
      'Язык структурированных запросов для работы с БД',
      'Тип базы данных',
      'Протокол передачи данных',
      'Формат хранения файлов',
    ],
    optionsEn: [
      'Structured Query Language for working with databases',
      'A type of database',
      'A data transfer protocol',
      'A file storage format',
    ],
    correctAnswer: 0,
    explanation: 'SQL (Structured Query Language) - это язык для управления и манипулирования данными в реляционных базах данных.',
    explanationEn: 'SQL (Structured Query Language) is a language for managing and manipulating data in relational databases.',
  },
  {
    id: 34,
    category: 'Databases',
    question: 'Что такое первичный ключ (Primary Key)?',
    questionEn: 'What is a Primary Key?',
    options: [
      'Уникальный идентификатор записи в таблице',
      'Пароль для доступа к БД',
      'Тип данных',
      'Метод шифрования',
    ],
    optionsEn: [
      'A unique identifier for a record in a table',
      'A password for database access',
      'A data type',
      'An encryption method',
    ],
    correctAnswer: 0,
    explanation: 'Первичный ключ - это столбец или набор столбцов, которые уникально идентифицируют каждую запись в таблице базы данных.',
    explanationEn: 'A primary key is a column or set of columns that uniquely identifies each record in a database table.',
  },
  {
    id: 35,
    category: 'Databases',
    question: 'Что такое индекс в базе данных?',
    questionEn: 'What is an index in a database?',
    options: [
      'Структура для ускорения поиска данных',
      'Тип таблицы',
      'Метод резервного копирования',
      'Способ шифрования',
    ],
    optionsEn: [
      'A structure for speeding up data search',
      'A type of table',
      'A backup method',
      'An encryption method',
    ],
    correctAnswer: 0,
    explanation: 'Индекс - это структура данных, которая повышает скорость операций поиска в базе данных за счёт дополнительного места для хранения.',
    explanationEn: 'An index is a data structure that increases the speed of search operations in a database at the cost of additional storage space.',
  },
  {
    id: 36,
    category: 'Databases',
    question: 'Что такое JOIN в SQL?',
    questionEn: 'What is JOIN in SQL?',
    options: [
      'Операция объединения данных из нескольких таблиц',
      'Создание новой таблицы',
      'Удаление данных',
      'Сортировка результатов',
    ],
    optionsEn: [
      'An operation for combining data from multiple tables',
      'Creating a new table',
      'Deleting data',
      'Sorting results',
    ],
    correctAnswer: 0,
    explanation: 'JOIN - это операция SQL, которая позволяет объединять строки из двух или более таблиц на основе связанных между ними столбцов.',
    explanationEn: 'JOIN is an SQL operation that allows combining rows from two or more tables based on related columns.',
  },
  {
    id: 37,
    category: 'Databases',
    question: 'Что такое NoSQL база данных?',
    questionEn: 'What is a NoSQL database?',
    options: [
      'Нереляционная БД для хранения неструктурированных данных',
      'Новая версия SQL',
      'База данных без запросов',
      'Метод шифрования данных',
    ],
    optionsEn: [
      'A non-relational database for storing unstructured data',
      'A new version of SQL',
      'A database without queries',
      'A data encryption method',
    ],
    correctAnswer: 0,
    explanation: 'NoSQL - это нереляционные базы данных, которые хранят данные в формате, отличном от табличного (документы, графы, ключ-значение и т.д.).',
    explanationEn: 'NoSQL refers to non-relational databases that store data in formats other than tables (documents, graphs, key-value, etc.).',
  },
  {
    id: 38,
    category: 'Databases',
    question: 'Что такое внешний ключ (Foreign Key)?',
    questionEn: 'What is a Foreign Key?',
    options: [
      'Столбец, ссылающийся на первичный ключ другой таблицы',
      'Ключ для внешнего доступа',
      'Пароль администратора',
      'Тип индекса',
    ],
    optionsEn: [
      'A column that references the primary key of another table',
      'A key for external access',
      'An administrator password',
      'A type of index',
    ],
    correctAnswer: 0,
    explanation: 'Внешний ключ - это столбец, который ссылается на первичный ключ другой таблицы, обеспечивая связь между таблицами.',
    explanationEn: 'A foreign key is a column that references the primary key of another table, establishing a link between tables.',
  },
  {
    id: 39,
    category: 'Databases',
    question: 'Что такое транзакция в базе данных?',
    questionEn: 'What is a transaction in a database?',
    options: [
      'Последовательность операций, выполняемых как единое целое',
      'Перевод денег',
      'Создание резервной копии',
      'Тип запроса',
    ],
    optionsEn: [
      'A sequence of operations executed as a single unit',
      'Money transfer',
      'Creating a backup',
      'A type of query',
    ],
    correctAnswer: 0,
    explanation: 'Транзакция - это последовательность операций с базой данных, которые выполняются как единое целое. Либо все операции выполняются успешно, либо ни одна.',
    explanationEn: 'A transaction is a sequence of database operations executed as a single unit. Either all operations succeed, or none do.',
  },
  {
    id: 40,
    category: 'Databases',
    question: 'Что такое денормализация?',
    questionEn: 'What is denormalization?',
    options: [
      'Добавление избыточности для повышения производительности',
      'Удаление дубликатов',
      'Шифрование данных',
      'Создание индексов',
    ],
    optionsEn: [
      'Adding redundancy to improve performance',
      'Removing duplicates',
      'Data encryption',
      'Creating indexes',
    ],
    correctAnswer: 0,
    explanation: 'Денормализация - это намеренное добавление избыточности в базу данных для повышения производительности чтения за счёт уменьшения количества JOIN-операций.',
    explanationEn: 'Denormalization is the intentional addition of redundancy to a database to improve read performance by reducing the number of JOIN operations.',
  },

  // Системный дизайн - 10 вопросов
  {
    id: 41,
    category: 'System Design',
    question: 'Что такое горизонтальное масштабирование?',
    questionEn: 'What is horizontal scaling?',
    options: [
      'Добавление большего количества серверов',
      'Увеличение мощности существующих серверов',
      'Оптимизация кода',
      'Сжатие данных',
    ],
    optionsEn: [
      'Adding more servers',
      'Increasing the power of existing servers',
      'Code optimization',
      'Data compression',
    ],
    correctAnswer: 0,
    explanation: 'Горизонтальное масштабирование (scaling out) - это добавление большего количества серверов для обработки нагрузки, в отличие от вертикального масштабирования (scaling up), которое увеличивает мощность существующих серверов.',
    explanationEn: 'Horizontal scaling (scaling out) is adding more servers to handle the load, as opposed to vertical scaling (scaling up), which increases the power of existing servers.',
  },
  {
    id: 42,
    category: 'System Design',
    question: 'Что такое кэширование?',
    questionEn: 'What is caching?',
    options: [
      'Хранение часто используемых данных в быстродоступном месте',
      'Удаление старых данных',
      'Шифрование информации',
      'Сжатие файлов',
    ],
    optionsEn: [
      'Storing frequently used data in a fast-access location',
      'Deleting old data',
      'Encrypting information',
      'Compressing files',
    ],
    correctAnswer: 0,
    explanation: 'Кэширование - это техника хранения копии данных в быстродоступном месте для ускорения последующих запросов к этим данным.',
    explanationEn: 'Caching is a technique of storing a copy of data in a fast-access location to speed up subsequent requests for that data.',
  },
  {
    id: 43,
    category: 'System Design',
    question: 'Что такое микросервисная архитектура?',
    questionEn: 'What is microservices architecture?',
    options: [
      'Разделение приложения на независимые сервисы',
      'Маленькое приложение',
      'Оптимизация кода',
      'Тип базы данных',
    ],
    optionsEn: [
      'Splitting an application into independent services',
      'A small application',
      'Code optimization',
      'A type of database',
    ],
    correctAnswer: 0,
    explanation: 'Микросервисная архитектура - это подход, при котором приложение разделяется на небольшие независимые сервисы, каждый из которых выполняет одну функцию.',
    explanationEn: 'Microservices architecture is an approach where an application is split into small independent services, each performing a single function.',
  },
  {
    id: 44,
    category: 'System Design',
    question: 'Что такое Load Balancer?',
    questionEn: 'What is a Load Balancer?',
    options: [
      'Распределитель нагрузки между серверами',
      'Инструмент для тестирования',
      'Тип базы данных',
      'Метод шифрования',
    ],
    optionsEn: [
      'A load distributor between servers',
      'A testing tool',
      'A type of database',
      'An encryption method',
    ],
    correctAnswer: 0,
    explanation: 'Load Balancer (балансировщик нагрузки) распределяет входящие запросы между несколькими серверами для обеспечения высокой доступности и производительности.',
    explanationEn: 'A Load Balancer distributes incoming requests among multiple servers to ensure high availability and performance.',
  },
  {
    id: 45,
    category: 'System Design',
    question: 'Что такое CDN?',
    questionEn: 'What is a CDN?',
    options: [
      'Сеть доставки контента для ускорения загрузки',
      'Тип протокола',
      'База данных',
      'Метод шифрования',
    ],
    optionsEn: [
      'A Content Delivery Network for faster loading',
      'A type of protocol',
      'A database',
      'An encryption method',
    ],
    correctAnswer: 0,
    explanation: 'CDN (Content Delivery Network) - это сеть серверов, распределённых географически, для быстрой доставки контента пользователям из ближайшего сервера.',
    explanationEn: 'CDN (Content Delivery Network) is a geographically distributed network of servers for fast content delivery to users from the nearest server.',
  },
  {
    id: 46,
    category: 'System Design',
    question: 'Что такое API Gateway?',
    questionEn: 'What is an API Gateway?',
    options: [
      'Единая точка входа для всех API запросов',
      'Тип базы данных',
      'Метод аутентификации',
      'Протокол передачи данных',
    ],
    optionsEn: [
      'A single entry point for all API requests',
      'A type of database',
      'An authentication method',
      'A data transfer protocol',
    ],
    correctAnswer: 0,
    explanation: 'API Gateway - это сервер, который служит единой точкой входа для всех клиентских запросов, маршрутизируя их к соответствующим микросервисам.',
    explanationEn: 'An API Gateway is a server that serves as a single entry point for all client requests, routing them to the appropriate microservices.',
  },
  {
    id: 47,
    category: 'System Design',
    question: 'Что такое CAP теорема?',
    questionEn: 'What is the CAP theorem?',
    options: [
      'Невозможность одновременно гарантировать Consistency, Availability, Partition tolerance',
      'Метод шифрования',
      'Протокол передачи данных',
      'Тип базы данных',
    ],
    optionsEn: [
      'The impossibility of simultaneously guaranteeing Consistency, Availability, and Partition tolerance',
      'An encryption method',
      'A data transfer protocol',
      'A type of database',
    ],
    correctAnswer: 0,
    explanation: 'CAP теорема утверждает, что распределённая система не может одновременно гарантировать согласованность (Consistency), доступность (Availability) и устойчивость к разделению (Partition tolerance).',
    explanationEn: 'The CAP theorem states that a distributed system cannot simultaneously guarantee Consistency, Availability, and Partition tolerance.',
  },
  {
    id: 48,
    category: 'System Design',
    question: 'Что такое очередь сообщений (Message Queue)?',
    questionEn: 'What is a Message Queue?',
    options: [
      'Асинхронный способ обмена сообщениями между сервисами',
      'Чат между пользователями',
      'Тип базы данных',
      'Метод логирования',
    ],
    optionsEn: [
      'An asynchronous way to exchange messages between services',
      'A chat between users',
      'A type of database',
      'A logging method',
    ],
    correctAnswer: 0,
    explanation: 'Message Queue - это механизм асинхронного обмена сообщениями между компонентами системы, обеспечивающий надёжную доставку и развязку сервисов.',
    explanationEn: 'A Message Queue is a mechanism for asynchronous message exchange between system components, ensuring reliable delivery and service decoupling.',
  },
  {
    id: 49,
    category: 'System Design',
    question: 'Что такое репликация базы данных?',
    questionEn: 'What is database replication?',
    options: [
      'Создание копий данных на нескольких серверах',
      'Сжатие данных',
      'Шифрование информации',
      'Удаление дубликатов',
    ],
    optionsEn: [
      'Creating copies of data on multiple servers',
      'Data compression',
      'Encrypting information',
      'Removing duplicates',
    ],
    correctAnswer: 0,
    explanation: 'Репликация - это процесс копирования данных на несколько серверов для обеспечения высокой доступности, отказоустойчивости и повышения производительности чтения.',
    explanationEn: 'Replication is the process of copying data to multiple servers to ensure high availability, fault tolerance, and improved read performance.',
  },
  {
    id: 50,
    category: 'System Design',
    question: 'Что такое шардирование (sharding)?',
    questionEn: 'What is sharding?',
    options: [
      'Разделение данных на части между несколькими серверами',
      'Сжатие данных',
      'Шифрование информации',
      'Резервное копирование',
    ],
    optionsEn: [
      'Splitting data into parts across multiple servers',
      'Data compression',
      'Encrypting information',
      'Backup',
    ],
    correctAnswer: 0,
    explanation: 'Шардирование - это метод горизонтального масштабирования, при котором данные распределяются между несколькими серверами (шардами) для повышения производительности.',
    explanationEn: 'Sharding is a horizontal scaling method where data is distributed across multiple servers (shards) to improve performance.',
  },

  // TypeScript - 10 вопросов
  {
    id: 51,
    category: 'TypeScript',
    question: 'Что такое TypeScript?',
    questionEn: 'What is TypeScript?',
    options: [
      'Надмножество JavaScript с добавлением статической типизации',
      'Новый язык программирования',
      'Библиотека для JavaScript',
      'Фреймворк для создания сайтов',
    ],
    optionsEn: [
      'A superset of JavaScript with static typing',
      'A new programming language',
      'A JavaScript library',
      'A framework for building websites',
    ],
    correctAnswer: 0,
    explanation: 'TypeScript - это язык программирования, являющийся надмножеством JavaScript с добавлением статической типизации и других возможностей.',
    explanationEn: 'TypeScript is a programming language that is a superset of JavaScript with static typing and other features.',
  },
  {
    id: 52,
    category: 'TypeScript',
    question: 'Что такое interface в TypeScript?',
    questionEn: 'What is an interface in TypeScript?',
    options: [
      'Способ описания структуры объекта',
      'Функция для работы с типами',
      'Метод оптимизации кода',
      'Альтернатива классам',
    ],
    optionsEn: [
      'A way to describe the structure of an object',
      'A function for working with types',
      'A code optimization method',
      'An alternative to classes',
    ],
    correctAnswer: 0,
    explanation: 'Interface в TypeScript - это способ описания структуры объекта, определяющий какие свойства и методы должен иметь объект.',
    explanationEn: 'An interface in TypeScript is a way to describe the structure of an object, defining what properties and methods an object should have.',
  },
  {
    id: 53,
    category: 'TypeScript',
    question: 'В чём разница между interface и type?',
    questionEn: 'What is the difference between interface and type?',
    options: [
      'interface можно расширять, type поддерживает union типы',
      'Нет разницы',
      'type быстрее',
      'interface устарел',
    ],
    optionsEn: [
      'interface can be extended, type supports union types',
      'No difference',
      'type is faster',
      'interface is deprecated',
    ],
    correctAnswer: 0,
    explanation: 'Interface можно расширять через extends и объединять объявления. Type поддерживает union и intersection типы, примитивы и кортежи.',
    explanationEn: 'Interface can be extended via extends and merged declarations. Type supports union and intersection types, primitives, and tuples.',
  },
  {
    id: 54,
    category: 'TypeScript',
    question: 'Что такое generic в TypeScript?',
    questionEn: 'What is a generic in TypeScript?',
    options: [
      'Параметризованный тип для создания переиспользуемого кода',
      'Специальный тип данных',
      'Метод оптимизации',
      'Способ импорта модулей',
    ],
    optionsEn: [
      'A parameterized type for creating reusable code',
      'A special data type',
      'An optimization method',
      'A way to import modules',
    ],
    correctAnswer: 0,
    explanation: 'Generic - это параметризованный тип, который позволяет создавать компоненты, работающие с различными типами данных, сохраняя типобезопасность.',
    explanationEn: 'A generic is a parameterized type that allows creating components that work with various data types while maintaining type safety.',
  },
  {
    id: 55,
    category: 'TypeScript',
    question: 'Что означает тип "any" в TypeScript?',
    questionEn: 'What does the "any" type mean in TypeScript?',
    options: [
      'Любой тип, отключает проверку типов',
      'Тип для чисел',
      'Тип для массивов',
      'Тип для объектов',
    ],
    optionsEn: [
      'Any type, disables type checking',
      'A type for numbers',
      'A type for arrays',
      'A type for objects',
    ],
    correctAnswer: 0,
    explanation: 'Тип any отключает проверку типов для переменной. Использовать его следует осторожно, так как теряется преимущество типизации.',
    explanationEn: 'The any type disables type checking for a variable. It should be used carefully as it loses the benefit of typing.',
  },
  {
    id: 56,
    category: 'TypeScript',
    question: 'Что такое enum в TypeScript?',
    questionEn: 'What is an enum in TypeScript?',
    options: [
      'Набор именованных констант',
      'Тип массива',
      'Способ создания функций',
      'Метод обработки ошибок',
    ],
    optionsEn: [
      'A set of named constants',
      'An array type',
      'A way to create functions',
      'An error handling method',
    ],
    correctAnswer: 0,
    explanation: 'Enum (перечисление) - это способ задать набор именованных констант, что делает код более читаемым и поддерживаемым.',
    explanationEn: 'An enum (enumeration) is a way to define a set of named constants, making code more readable and maintainable.',
  },
  {
    id: 57,
    category: 'TypeScript',
    question: 'Что такое union type?',
    questionEn: 'What is a union type?',
    options: [
      'Тип, который может быть одним из нескольких типов',
      'Объединение массивов',
      'Слияние объектов',
      'Способ наследования',
    ],
    optionsEn: [
      'A type that can be one of several types',
      'Merging arrays',
      'Merging objects',
      'A way of inheritance',
    ],
    correctAnswer: 0,
    explanation: 'Union type (объединённый тип) позволяет переменной быть одним из нескольких типов. Записывается через символ |, например: string | number.',
    explanationEn: 'A union type allows a variable to be one of several types. Written with the | symbol, for example: string | number.',
  },
  {
    id: 58,
    category: 'TypeScript',
    question: 'Что такое type guard?',
    questionEn: 'What is a type guard?',
    options: [
      'Проверка типа во время выполнения для сужения типа',
      'Защита от ошибок компиляции',
      'Способ шифрования типов',
      'Метод оптимизации',
    ],
    optionsEn: [
      'A runtime type check for narrowing types',
      'Protection from compilation errors',
      'A way to encrypt types',
      'An optimization method',
    ],
    correctAnswer: 0,
    explanation: 'Type guard - это выражение, которое проверяет тип во время выполнения и позволяет TypeScript сузить тип переменной в определённом блоке кода.',
    explanationEn: 'A type guard is an expression that checks the type at runtime and allows TypeScript to narrow the type of a variable in a specific code block.',
  },
  {
    id: 59,
    category: 'TypeScript',
    question: 'Что такое "never" тип?',
    questionEn: 'What is the "never" type?',
    options: [
      'Тип для функций, которые никогда не возвращают значение',
      'Пустой тип',
      'Тип для null',
      'Альтернатива undefined',
    ],
    optionsEn: [
      'A type for functions that never return a value',
      'An empty type',
      'A type for null',
      'An alternative to undefined',
    ],
    correctAnswer: 0,
    explanation: 'Тип never используется для функций, которые никогда не возвращают значение (бросают исключение или содержат бесконечный цикл).',
    explanationEn: 'The never type is used for functions that never return a value (throw an exception or contain an infinite loop).',
  },
  {
    id: 60,
    category: 'TypeScript',
    question: 'Что такое "readonly" модификатор?',
    questionEn: 'What is the "readonly" modifier?',
    options: [
      'Делает свойство доступным только для чтения',
      'Скрывает свойство',
      'Делает свойство обязательным',
      'Удаляет свойство',
    ],
    optionsEn: [
      'Makes a property read-only',
      'Hides a property',
      'Makes a property required',
      'Removes a property',
    ],
    correctAnswer: 0,
    explanation: 'Модификатор readonly делает свойство доступным только для чтения. После инициализации его значение нельзя изменить.',
    explanationEn: 'The readonly modifier makes a property read-only. After initialization, its value cannot be changed.',
  },

  // Node.js - 10 вопросов
  {
    id: 61,
    category: 'Node.js',
    question: 'Что такое Node.js?',
    questionEn: 'What is Node.js?',
    options: [
      'Среда выполнения JavaScript на сервере',
      'Фреймворк для frontend',
      'База данных',
      'Язык программирования',
    ],
    optionsEn: [
      'A JavaScript runtime for the server',
      'A frontend framework',
      'A database',
      'A programming language',
    ],
    correctAnswer: 0,
    explanation: 'Node.js - это среда выполнения JavaScript, построенная на движке V8 от Chrome, позволяющая запускать JavaScript на сервере.',
    explanationEn: 'Node.js is a JavaScript runtime built on Chrome\'s V8 engine, allowing JavaScript to run on the server.',
  },
  {
    id: 62,
    category: 'Node.js',
    question: 'Что такое npm?',
    questionEn: 'What is npm?',
    options: [
      'Пакетный менеджер для Node.js',
      'Сервер для Node.js',
      'База данных',
      'Фреймворк',
    ],
    optionsEn: [
      'A package manager for Node.js',
      'A server for Node.js',
      'A database',
      'A framework',
    ],
    correctAnswer: 0,
    explanation: 'npm (Node Package Manager) - это пакетный менеджер для JavaScript, позволяющий устанавливать, обновлять и управлять зависимостями проекта.',
    explanationEn: 'npm (Node Package Manager) is a package manager for JavaScript that allows installing, updating, and managing project dependencies.',
  },
  {
    id: 63,
    category: 'Node.js',
    question: 'Что такое package.json?',
    questionEn: 'What is package.json?',
    options: [
      'Файл с метаданными и зависимостями проекта',
      'Конфигурация сервера',
      'Файл с переменными окружения',
      'Лог-файл',
    ],
    optionsEn: [
      'A file with project metadata and dependencies',
      'Server configuration',
      'Environment variables file',
      'Log file',
    ],
    correctAnswer: 0,
    explanation: 'package.json - это файл, содержащий метаданные проекта (название, версия, скрипты) и список зависимостей.',
    explanationEn: 'package.json is a file containing project metadata (name, version, scripts) and a list of dependencies.',
  },
  {
    id: 64,
    category: 'Node.js',
    question: 'Что такое Express.js?',
    questionEn: 'What is Express.js?',
    options: [
      'Минималистичный веб-фреймворк для Node.js',
      'База данных',
      'Шаблонизатор',
      'ORM для Node.js',
    ],
    optionsEn: [
      'A minimalist web framework for Node.js',
      'A database',
      'A template engine',
      'An ORM for Node.js',
    ],
    correctAnswer: 0,
    explanation: 'Express.js - это минималистичный и гибкий веб-фреймворк для Node.js, предоставляющий набор функций для создания веб-приложений и API.',
    explanationEn: 'Express.js is a minimalist and flexible web framework for Node.js, providing a set of features for building web applications and APIs.',
  },
  {
    id: 65,
    category: 'Node.js',
    question: 'Что такое middleware в Express?',
    questionEn: 'What is middleware in Express?',
    options: [
      'Функция, обрабатывающая запрос между получением и ответом',
      'База данных',
      'Шаблон проектирования',
      'Метод маршрутизации',
    ],
    optionsEn: [
      'A function that processes a request between receiving and responding',
      'A database',
      'A design pattern',
      'A routing method',
    ],
    correctAnswer: 0,
    explanation: 'Middleware - это функции, которые имеют доступ к объектам запроса и ответа и могут выполнять код, изменять запрос/ответ или завершать цикл обработки.',
    explanationEn: 'Middleware are functions that have access to request and response objects and can execute code, modify request/response, or end the processing cycle.',
  },
  {
    id: 66,
    category: 'Node.js',
    question: 'Что такое модуль fs в Node.js?',
    questionEn: 'What is the fs module in Node.js?',
    options: [
      'Модуль для работы с файловой системой',
      'Модуль для работы с сетью',
      'Модуль для шифрования',
      'Модуль для тестирования',
    ],
    optionsEn: [
      'A module for working with the file system',
      'A module for networking',
      'A module for encryption',
      'A module for testing',
    ],
    correctAnswer: 0,
    explanation: 'Модуль fs (file system) предоставляет API для взаимодействия с файловой системой: чтение, запись, удаление файлов и директорий.',
    explanationEn: 'The fs (file system) module provides an API for interacting with the file system: reading, writing, deleting files and directories.',
  },
  {
    id: 67,
    category: 'Node.js',
    question: 'Что такое process.env?',
    questionEn: 'What is process.env?',
    options: [
      'Объект с переменными окружения',
      'Информация о процессоре',
      'Список запущенных процессов',
      'Конфигурация памяти',
    ],
    optionsEn: [
      'An object with environment variables',
      'Processor information',
      'List of running processes',
      'Memory configuration',
    ],
    correctAnswer: 0,
    explanation: 'process.env - это объект, содержащий переменные окружения. Используется для хранения конфигурации (API ключи, настройки БД и т.д.).',
    explanationEn: 'process.env is an object containing environment variables. Used for storing configuration (API keys, database settings, etc.).',
  },
  {
    id: 68,
    category: 'Node.js',
    question: 'Что такое callback hell?',
    questionEn: 'What is callback hell?',
    options: [
      'Глубокая вложенность колбэков, ухудшающая читаемость',
      'Ошибка в коде',
      'Тип атаки',
      'Метод оптимизации',
    ],
    optionsEn: [
      'Deep nesting of callbacks that reduces readability',
      'A code error',
      'A type of attack',
      'An optimization method',
    ],
    correctAnswer: 0,
    explanation: 'Callback hell - это анти-паттерн с глубокой вложенностью колбэков, делающий код трудночитаемым. Решается через Promises или async/await.',
    explanationEn: 'Callback hell is an anti-pattern with deeply nested callbacks that makes code hard to read. Solved through Promises or async/await.',
  },
  {
    id: 69,
    category: 'Node.js',
    question: 'Что такое Buffer в Node.js?',
    questionEn: 'What is a Buffer in Node.js?',
    options: [
      'Класс для работы с бинарными данными',
      'Тип массива',
      'Метод кэширования',
      'Способ логирования',
    ],
    optionsEn: [
      'A class for working with binary data',
      'An array type',
      'A caching method',
      'A logging method',
    ],
    correctAnswer: 0,
    explanation: 'Buffer - это класс для работы с бинарными данными напрямую. Используется при работе с потоками, файлами и сетевыми операциями.',
    explanationEn: 'Buffer is a class for working with binary data directly. Used when working with streams, files, and network operations.',
  },
  {
    id: 70,
    category: 'Node.js',
    question: 'Что такое cluster в Node.js?',
    questionEn: 'What is cluster in Node.js?',
    options: [
      'Модуль для создания дочерних процессов для многоядерных систем',
      'Тип базы данных',
      'Метод кэширования',
      'Способ логирования',
    ],
    optionsEn: [
      'A module for creating child processes for multi-core systems',
      'A type of database',
      'A caching method',
      'A logging method',
    ],
    correctAnswer: 0,
    explanation: 'Модуль cluster позволяет создавать дочерние процессы (workers), которые разделяют один серверный порт, используя все ядра процессора.',
    explanationEn: 'The cluster module allows creating child processes (workers) that share a single server port, utilizing all CPU cores.',
  },

  // CSS - 10 вопросов
  {
    id: 71,
    category: 'CSS',
    question: 'Что такое Flexbox?',
    questionEn: 'What is Flexbox?',
    options: [
      'Модель разметки для создания гибких макетов',
      'CSS фреймворк',
      'Препроцессор CSS',
      'JavaScript библиотека',
    ],
    optionsEn: [
      'A layout model for creating flexible layouts',
      'A CSS framework',
      'A CSS preprocessor',
      'A JavaScript library',
    ],
    correctAnswer: 0,
    explanation: 'Flexbox - это модель CSS-разметки, предназначенная для создания гибких и адаптивных макетов с удобным выравниванием элементов.',
    explanationEn: 'Flexbox is a CSS layout model designed for creating flexible and responsive layouts with convenient element alignment.',
  },
  {
    id: 72,
    category: 'CSS',
    question: 'Что такое CSS Grid?',
    questionEn: 'What is CSS Grid?',
    options: [
      'Двумерная система разметки для создания сложных макетов',
      'Таблица в CSS',
      'Фреймворк',
      'Метод анимации',
    ],
    optionsEn: [
      'A two-dimensional layout system for creating complex layouts',
      'A table in CSS',
      'A framework',
      'An animation method',
    ],
    correctAnswer: 0,
    explanation: 'CSS Grid - это двумерная система разметки, позволяющая создавать сложные макеты с строками и столбцами одновременно.',
    explanationEn: 'CSS Grid is a two-dimensional layout system that allows creating complex layouts with rows and columns simultaneously.',
  },
  {
    id: 73,
    category: 'CSS',
    question: 'Что такое специфичность (specificity) в CSS?',
    questionEn: 'What is specificity in CSS?',
    options: [
      'Приоритет применения стилей на основе селекторов',
      'Скорость загрузки стилей',
      'Размер CSS файла',
      'Количество правил',
    ],
    optionsEn: [
      'Priority of style application based on selectors',
      'Style loading speed',
      'CSS file size',
      'Number of rules',
    ],
    correctAnswer: 0,
    explanation: 'Специфичность определяет, какие CSS правила применяются к элементу при конфликте. Рассчитывается на основе типа селекторов.',
    explanationEn: 'Specificity determines which CSS rules apply to an element when there is a conflict. Calculated based on selector types.',
  },
  {
    id: 74,
    category: 'CSS',
    question: 'Что такое псевдокласс :hover?',
    questionEn: 'What is the :hover pseudo-class?',
    options: [
      'Применяет стили при наведении курсора на элемент',
      'Скрывает элемент',
      'Добавляет анимацию',
      'Изменяет позицию элемента',
    ],
    optionsEn: [
      'Applies styles when hovering over an element',
      'Hides an element',
      'Adds animation',
      'Changes element position',
    ],
    correctAnswer: 0,
    explanation: 'Псевдокласс :hover применяет стили к элементу, когда пользователь наводит на него курсор мыши.',
    explanationEn: 'The :hover pseudo-class applies styles to an element when the user hovers over it with the mouse cursor.',
  },
  {
    id: 75,
    category: 'CSS',
    question: 'Что такое box-sizing: border-box?',
    questionEn: 'What is box-sizing: border-box?',
    options: [
      'Включает padding и border в общую ширину/высоту элемента',
      'Добавляет рамку элементу',
      'Скрывает границы',
      'Изменяет тип элемента',
    ],
    optionsEn: [
      'Includes padding and border in the total width/height of an element',
      'Adds a border to an element',
      'Hides borders',
      'Changes element type',
    ],
    correctAnswer: 0,
    explanation: 'box-sizing: border-box включает padding и border в указанную ширину и высоту элемента, упрощая расчёт размеров.',
    explanationEn: 'box-sizing: border-box includes padding and border in the specified width and height of an element, simplifying size calculations.',
  },
  {
    id: 76,
    category: 'CSS',
    question: 'Что такое z-index?',
    questionEn: 'What is z-index?',
    options: [
      'Свойство, определяющее порядок наложения элементов',
      'Размер элемента',
      'Прозрачность',
      'Позиция по оси X',
    ],
    optionsEn: [
      'A property that determines the stacking order of elements',
      'Element size',
      'Transparency',
      'Position on the X axis',
    ],
    correctAnswer: 0,
    explanation: 'z-index определяет порядок наложения позиционированных элементов. Элементы с большим z-index отображаются поверх элементов с меньшим.',
    explanationEn: 'z-index determines the stacking order of positioned elements. Elements with a higher z-index are displayed above elements with a lower one.',
  },
  {
    id: 77,
    category: 'CSS',
    question: 'Что такое media queries?',
    questionEn: 'What are media queries?',
    options: [
      'Правила для применения стилей в зависимости от характеристик устройства',
      'Запросы к серверу',
      'Метод загрузки изображений',
      'Способ анимации',
    ],
    optionsEn: [
      'Rules for applying styles based on device characteristics',
      'Server requests',
      'An image loading method',
      'An animation method',
    ],
    correctAnswer: 0,
    explanation: 'Media queries позволяют применять разные CSS стили в зависимости от характеристик устройства (ширина экрана, ориентация и т.д.).',
    explanationEn: 'Media queries allow applying different CSS styles based on device characteristics (screen width, orientation, etc.).',
  },
  {
    id: 78,
    category: 'CSS',
    question: 'Что такое CSS переменные (custom properties)?',
    questionEn: 'What are CSS variables (custom properties)?',
    options: [
      'Пользовательские значения, которые можно переиспользовать',
      'Стандартные значения CSS',
      'JavaScript переменные в CSS',
      'Препроцессорные функции',
    ],
    optionsEn: [
      'Custom values that can be reused',
      'Standard CSS values',
      'JavaScript variables in CSS',
      'Preprocessor functions',
    ],
    correctAnswer: 0,
    explanation: 'CSS переменные (--custom-property) позволяют определять значения для переиспользования в CSS, упрощая поддержку и изменение стилей.',
    explanationEn: 'CSS variables (--custom-property) allow defining values for reuse in CSS, simplifying style maintenance and changes.',
  },
  {
    id: 79,
    category: 'CSS',
    question: 'В чём разница между margin и padding?',
    questionEn: 'What is the difference between margin and padding?',
    options: [
      'margin - внешний отступ, padding - внутренний',
      'Нет разницы',
      'margin больше padding',
      'padding только для блочных элементов',
    ],
    optionsEn: [
      'margin is outer spacing, padding is inner spacing',
      'No difference',
      'margin is larger than padding',
      'padding is only for block elements',
    ],
    correctAnswer: 0,
    explanation: 'Margin - это внешний отступ (пространство снаружи элемента), padding - внутренний отступ (пространство между содержимым и границей элемента).',
    explanationEn: 'Margin is the outer spacing (space outside the element), padding is the inner spacing (space between the content and the element border).',
  },
  {
    id: 80,
    category: 'CSS',
    question: 'Что такое position: absolute?',
    questionEn: 'What is position: absolute?',
    options: [
      'Позиционирует элемент относительно ближайшего позиционированного предка',
      'Фиксирует элемент на экране',
      'Размещает элемент в потоке',
      'Скрывает элемент',
    ],
    optionsEn: [
      'Positions an element relative to its closest positioned ancestor',
      'Fixes an element on the screen',
      'Places an element in the flow',
      'Hides an element',
    ],
    correctAnswer: 0,
    explanation: 'position: absolute позиционирует элемент относительно ближайшего позиционированного предка (не static). Элемент удаляется из нормального потока документа.',
    explanationEn: 'position: absolute positions an element relative to its closest positioned ancestor (not static). The element is removed from the normal document flow.',
  },

  // Git - 10 вопросов
  {
    id: 81,
    category: 'Git',
    question: 'Что такое Git?',
    questionEn: 'What is Git?',
    options: [
      'Распределённая система контроля версий',
      'Язык программирования',
      'База данных',
      'Веб-сервер',
    ],
    optionsEn: [
      'A distributed version control system',
      'A programming language',
      'A database',
      'A web server',
    ],
    correctAnswer: 0,
    explanation: 'Git - это распределённая система контроля версий, которая отслеживает изменения в файлах и позволяет координировать работу над проектом.',
    explanationEn: 'Git is a distributed version control system that tracks changes in files and allows coordinating work on a project.',
  },
  {
    id: 82,
    category: 'Git',
    question: 'Что делает команда git clone?',
    questionEn: 'What does the git clone command do?',
    options: [
      'Копирует удалённый репозиторий на локальную машину',
      'Создаёт новую ветку',
      'Удаляет репозиторий',
      'Сохраняет изменения',
    ],
    optionsEn: [
      'Copies a remote repository to the local machine',
      'Creates a new branch',
      'Deletes a repository',
      'Saves changes',
    ],
    correctAnswer: 0,
    explanation: 'git clone создаёт копию удалённого репозитория на вашем компьютере, включая всю историю коммитов.',
    explanationEn: 'git clone creates a copy of a remote repository on your computer, including the entire commit history.',
  },
  {
    id: 83,
    category: 'Git',
    question: 'Что делает команда git commit?',
    questionEn: 'What does the git commit command do?',
    options: [
      'Сохраняет изменения в локальном репозитории',
      'Отправляет изменения на сервер',
      'Скачивает изменения',
      'Удаляет файлы',
    ],
    optionsEn: [
      'Saves changes to the local repository',
      'Sends changes to the server',
      'Downloads changes',
      'Deletes files',
    ],
    correctAnswer: 0,
    explanation: 'git commit сохраняет проиндексированные (staged) изменения в локальном репозитории с сообщением о коммите.',
    explanationEn: 'git commit saves staged changes to the local repository with a commit message.',
  },
  {
    id: 84,
    category: 'Git',
    question: 'В чём разница между git fetch и git pull?',
    questionEn: 'What is the difference between git fetch and git pull?',
    options: [
      'fetch скачивает изменения, pull скачивает и сливает',
      'Нет разницы',
      'pull быстрее',
      'fetch устарел',
    ],
    optionsEn: [
      'fetch downloads changes, pull downloads and merges',
      'No difference',
      'pull is faster',
      'fetch is deprecated',
    ],
    correctAnswer: 0,
    explanation: 'git fetch скачивает изменения из удалённого репозитория без слияния. git pull - это fetch + merge, он сразу сливает изменения в текущую ветку.',
    explanationEn: 'git fetch downloads changes from the remote repository without merging. git pull is fetch + merge, it immediately merges changes into the current branch.',
  },
  {
    id: 85,
    category: 'Git',
    question: 'Что такое git branch?',
    questionEn: 'What is git branch?',
    options: [
      'Команда для создания и управления ветками',
      'Команда для удаления файлов',
      'Команда для просмотра истории',
      'Команда для слияния',
    ],
    optionsEn: [
      'A command for creating and managing branches',
      'A command for deleting files',
      'A command for viewing history',
      'A command for merging',
    ],
    correctAnswer: 0,
    explanation: 'git branch позволяет создавать, просматривать, переименовывать и удалять ветки в репозитории.',
    explanationEn: 'git branch allows creating, viewing, renaming, and deleting branches in a repository.',
  },
  {
    id: 86,
    category: 'Git',
    question: 'Что делает git merge?',
    questionEn: 'What does git merge do?',
    options: [
      'Объединяет две ветки',
      'Удаляет ветку',
      'Создаёт новый коммит',
      'Отменяет изменения',
    ],
    optionsEn: [
      'Merges two branches',
      'Deletes a branch',
      'Creates a new commit',
      'Undoes changes',
    ],
    correctAnswer: 0,
    explanation: 'git merge объединяет историю указанной ветки с текущей веткой, создавая коммит слияния при необходимости.',
    explanationEn: 'git merge combines the history of the specified branch with the current branch, creating a merge commit if necessary.',
  },
  {
    id: 87,
    category: 'Git',
    question: 'Что такое git rebase?',
    questionEn: 'What is git rebase?',
    options: [
      'Перемещает коммиты на новую базу',
      'Удаляет коммиты',
      'Создаёт резервную копию',
      'Отменяет слияние',
    ],
    optionsEn: [
      'Moves commits to a new base',
      'Deletes commits',
      'Creates a backup',
      'Undoes a merge',
    ],
    correctAnswer: 0,
    explanation: 'git rebase перемещает или объединяет последовательность коммитов на новую базу. Создаёт линейную историю коммитов.',
    explanationEn: 'git rebase moves or combines a sequence of commits to a new base. Creates a linear commit history.',
  },
  {
    id: 88,
    category: 'Git',
    question: 'Что такое .gitignore?',
    questionEn: 'What is .gitignore?',
    options: [
      'Файл со списком игнорируемых файлов и папок',
      'Скрытая папка Git',
      'Конфигурация Git',
      'Лог-файл',
    ],
    optionsEn: [
      'A file with a list of ignored files and folders',
      'A hidden Git folder',
      'Git configuration',
      'A log file',
    ],
    correctAnswer: 0,
    explanation: '.gitignore - это файл, содержащий паттерны файлов и папок, которые Git должен игнорировать (не отслеживать).',
    explanationEn: '.gitignore is a file containing patterns of files and folders that Git should ignore (not track).',
  },
  {
    id: 89,
    category: 'Git',
    question: 'Что делает git stash?',
    questionEn: 'What does git stash do?',
    options: [
      'Временно сохраняет незакоммиченные изменения',
      'Удаляет изменения',
      'Создаёт коммит',
      'Переключает ветку',
    ],
    optionsEn: [
      'Temporarily saves uncommitted changes',
      'Deletes changes',
      'Creates a commit',
      'Switches branches',
    ],
    correctAnswer: 0,
    explanation: 'git stash временно сохраняет незакоммиченные изменения, позволяя переключиться на другую задачу и вернуться к ним позже.',
    explanationEn: 'git stash temporarily saves uncommitted changes, allowing you to switch to another task and return to them later.',
  },
  {
    id: 90,
    category: 'Git',
    question: 'Что такое pull request (merge request)?',
    questionEn: 'What is a pull request (merge request)?',
    options: [
      'Запрос на слияние изменений из одной ветки в другую',
      'Запрос на скачивание кода',
      'Запрос на удаление ветки',
      'Запрос на создание репозитория',
    ],
    optionsEn: [
      'A request to merge changes from one branch to another',
      'A request to download code',
      'A request to delete a branch',
      'A request to create a repository',
    ],
    correctAnswer: 0,
    explanation: 'Pull request - это запрос на слияние изменений из одной ветки в другую, обычно с возможностью code review перед слиянием.',
    explanationEn: 'A pull request is a request to merge changes from one branch to another, usually with the option of code review before merging.',
  },
]

// Категории для отображения (русский и английский)
export const categoryNames: Record<string, { ru: string; en: string }> = {
  'JavaScript': { ru: 'JavaScript', en: 'JavaScript' },
  'React': { ru: 'React', en: 'React' },
  'Algorithms': { ru: 'Алгоритмы', en: 'Algorithms' },
  'Databases': { ru: 'Базы данных', en: 'Databases' },
  'System Design': { ru: 'Системный дизайн', en: 'System Design' },
  'TypeScript': { ru: 'TypeScript', en: 'TypeScript' },
  'Node.js': { ru: 'Node.js', en: 'Node.js' },
  'CSS': { ru: 'CSS', en: 'CSS' },
  'Git': { ru: 'Git', en: 'Git' },
}

// Функция для получения локализованного вопроса
export const getLocalizedQuestion = (question: Question, lang: string) => {
  const isEn = lang === 'en'
  return {
    ...question,
    question: isEn ? question.questionEn : question.question,
    options: isEn ? question.optionsEn : question.options,
    explanation: isEn ? question.explanationEn : question.explanation,
  }
}

// Функция для получения локализованного названия категории
export const getLocalizedCategoryName = (category: string, lang: string) => {
  const names = categoryNames[category]
  if (!names) return category
  return lang === 'en' ? names.en : names.ru
}